/**
 * CYBERDUDEBIVASH — Vibe Code Security Scanner :: Cloudflare Worker Handler
 * ------------------------------------------------------------------------
 * v2.0.0 — drop-in replacement for the v29 handler. Same export surface,
 * same routes, same call signature, so index.js needs NO router changes:
 *
 *   import { handleVibeCodeScan, handleVibeCodePatterns } from './handlers/vibeCodeScanner.js';
 *   POST /api/vibe-code/scan      -> handleVibeCodeScan(request, env, authCtx)
 *   GET  /api/vibe-code/patterns  -> handleVibeCodePatterns(request, env)
 *
 * Tier is read from authCtx.tier (FREE | STARTER | PRO | ENTERPRISE | MSSP),
 * exactly as resolveAuthV5() produces it. FREE / anonymous callers are gated
 * (full grade + severity counts + top 3 findings; the rest locked behind the
 * ₹999 Starter unlock). STARTER and above get the full report.
 *
 * SECURITY: the plan is taken ONLY from authCtx — never from the request body —
 * so a free caller cannot self-upgrade by sending {"tier":"pro"}.
 *
 * The three engine files live in ./vibe-code/ to avoid filename collisions
 * with other handlers (engine.js / rules.js / util.js are generic names).
 */
'use strict';

import { scanVibeCode } from './engine.js';
import { RULES } from './rules.js';

const FREE_LINE_LIMIT = 800;
const FREE_PREVIEW_COUNT = 3;
const UNLOCK_PRICE = '\u20B9999'; // ₹999 — keep in sync with the pricing engine

function json(body, status = 200, extraHeaders = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', ...extraHeaders },
  });
}

/** Normalize any plan string (incl. resolveAuthV5 UPPERCASE) to a canonical tier. */
function normalizeTier(tier) {
  const t = String(tier || 'free').toLowerCase();
  if (t.includes('enterprise') || t.includes('mssp')) return 'enterprise';
  if (t.includes('pro')) return 'pro';
  if (t.includes('starter')) return 'starter';
  return 'free';
}
const isPaid = (tier) => normalizeTier(tier) !== 'free';

/** Resolve the caller's tier from authCtx ONLY. Anonymous / unauth => free. */
function tierFromAuth(authCtx) {
  if (authCtx && typeof authCtx === 'object' && authCtx.tier) return normalizeTier(authCtx.tier);
  return 'free';
}

/**
 * Apply the monetization gate to a raw engine result.
 * Paid tiers get everything. Free tier gets the full risk picture (so the
 * value is visible) but only the top findings in detail — the rest are locked.
 */
export function applyTierGate(result, tier) {
  if (!result.ok) return result;
  if (isPaid(tier)) {
    return { ...result, tier: normalizeTier(tier), gated: false };
  }
  const revealed = result.findings.slice(0, FREE_PREVIEW_COUNT);
  const lockedCount = Math.max(0, result.findings.length - revealed.length);
  const lockedPreview = result.findings.slice(FREE_PREVIEW_COUNT).map((f) => ({
    rule_id: f.rule_id, title: f.title, category: f.category,
    severity: f.severity, confidence: f.confidence, line: f.line,
    locked: true,
  }));
  return {
    ...result,
    tier: 'free',
    gated: true,
    findings: revealed,
    locked_findings: lockedPreview,
    locked_count: lockedCount,
    upgrade: {
      message: lockedCount > 0
        ? `${lockedCount} more finding${lockedCount === 1 ? '' : 's'} (with full remediation and a downloadable report) are available on a paid plan.`
        : 'Upgrade for repository scanning, downloadable reports, and API access.',
      unlock_price: UNLOCK_PRICE,
      cta: 'Unlock full report',
    },
  };
}

/** Build a clean Markdown report (paid tiers / report download). */
export function renderMarkdownReport(result) {
  const lines = [];
  lines.push(`# Vibe Code Security Scan Report`);
  lines.push(`*Generated by CYBERDUDEBIVASH Vibe Code Security Scanner (engine v${result.engine_version})*`);
  lines.push('');
  lines.push(`- **Language:** ${result.language}`);
  lines.push(`- **Security grade:** ${result.grade}  •  **Risk score:** ${result.risk_score}/100`);
  lines.push(`- **Findings:** ${result.total_findings} ` +
    `(Critical ${result.severity_counts.CRITICAL}, High ${result.severity_counts.HIGH}, ` +
    `Medium ${result.severity_counts.MEDIUM}, Low ${result.severity_counts.LOW})`);
  lines.push(`- **Scanned:** ${result.stats.lines_scanned} lines in ${result.stats.duration_ms} ms`);
  lines.push('');
  if (!result.findings.length) { lines.push('No issues detected by the current rule set. _Heuristic scan — not a substitute for manual review._'); return lines.join('\n'); }
  result.findings.forEach((f, i) => {
    lines.push(`## ${i + 1}. ${f.title}  \`${f.severity}\``);
    lines.push(`**Line ${f.line}** • ${f.category} • ${f.cwe}` +
      (f.owasp ? ` • ${f.owasp}` : '') + (f.owasp_llm ? ` • ${f.owasp_llm}` : '') +
      ` • confidence: ${f.confidence}`);
    lines.push('');
    lines.push('```\n' + f.snippet + '\n```');
    lines.push(`**Why AI writes this:** ${f.why_ai}`);
    lines.push(`**How to fix:** ${f.remediation}`);
    if (f.evidence) lines.push(`*Evidence:* ${f.evidence}`);
    lines.push('');
  });
  lines.push('---');
  lines.push('_This is a fast static heuristic scan. It finds the high-frequency classes of flaw that AI assistants emit; it does not replace full dataflow taint analysis or a manual review for business-logic bugs._');
  return lines.join('\n');
}

/** Public rule catalog (array form) — reused by the patterns endpoint and docs. */
export function vibeRuleCatalog() {
  return RULES.map((r) => ({
    id: r.id, title: r.title, category: r.category, severity: r.severity,
    cwe: r.cwe, owasp: r.owasp, owasp_llm: r.owasp_llm, languages: r.langs,
  }));
}

/**
 * POST /api/vibe-code/scan
 * @param {Request} request
 * @param {object}  env      Worker env (env.DB = D1 binding)
 * @param {object} [authCtx] resolveAuthV5 result; authCtx.tier drives gating
 */
export async function handleVibeCodeScan(request, env, authCtx) {
  if (request.method !== 'POST') return json({ ok: false, error: 'METHOD_NOT_ALLOWED' }, 405);

  let body;
  try { body = await request.json(); }
  catch { return json({ ok: false, error: 'BAD_JSON', message: 'Request body must be JSON.' }, 400); }

  const code = body && typeof body.code === 'string' ? body.code : '';
  if (!code.trim()) return json({ ok: false, error: 'EMPTY_CODE', message: 'Provide code to scan in the "code" field.' }, 400);

  // Plan comes from auth context ONLY — body.tier is intentionally ignored.
  const tier = tierFromAuth(authCtx);

  // Free tier: cap the amount of code analysed per scan.
  let scanCode = code;
  let freeLineCapped = false;
  if (!isPaid(tier)) {
    const codeLines = code.split('\n');
    if (codeLines.length > FREE_LINE_LIMIT) { scanCode = codeLines.slice(0, FREE_LINE_LIMIT).join('\n'); freeLineCapped = true; }
  }

  const raw = scanVibeCode(scanCode, { language: body.language, filename: body.filename });
  if (!raw.ok) return json(raw, 400);

  const gated = applyTierGate(raw, tier);
  if (freeLineCapped) gated.free_line_cap = FREE_LINE_LIMIT;

  // Best-effort metric. Never blocks or fails the response.
  try {
    if (env && env.DB && env.DB.prepare) {
      await env.DB.prepare(
        'UPDATE platform_metrics SET value_int = value_int + 1 WHERE key = ?'
      ).bind('vibe_code_scans_total').run();
    }
  } catch (_) { /* metrics are best-effort */ }

  return json(gated);
}

/**
 * GET /api/vibe-code/patterns
 * Public, cacheable rule catalog — great for the landing page and SEO.
 */
export async function handleVibeCodePatterns(request, env) {
  const patterns = vibeRuleCatalog();
  return json(
    { ok: true, engine_version: '2.0.0', count: patterns.length, patterns },
    200,
    { 'cache-control': 'public, max-age=3600' },
  );
}

export default {
  handleVibeCodeScan,
  handleVibeCodePatterns,
  applyTierGate,
  renderMarkdownReport,
  vibeRuleCatalog,
};
