apiVersion: v1
kind: ConfigMap
metadata:
  name: cdb-macos-config
  namespace: cdb-production
data:
  ENVIRONMENT:        "production"
  WORKERS:            "4"
  QDRANT_URL:         "http://cdb-qdrant:6333"
  KAFKA_BROKERS:      "cdb-kafka:9092"
  OTEL_SERVICE_NAME:  "cdb-macos-api"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://cdb-otel-collector:4317"
  ALLOWED_ORIGINS:    "https://cyberdudebivash.in,https://www.cyberdudebivash.in"
