apiVersion: v1
kind: Service
metadata:
  name: cdb-macos-api
  namespace: cdb-production
  labels:
    app: cdb-macos-api
spec:
  selector:
    app: cdb-macos-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cdb-macos-ingress
  namespace: cdb-production
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect:          "true"
    nginx.ingress.kubernetes.io/rate-limit:            "100"
    nginx.ingress.kubernetes.io/rate-limit-window:     "1m"
    nginx.ingress.kubernetes.io/proxy-body-size:       "1m"
    cert-manager.io/cluster-issuer:                   "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.cyberdudebivash.in
      secretName: cdb-macos-tls
  rules:
    - host: api.cyberdudebivash.in
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: cdb-macos-api
                port:
                  number: 80
